usuarios = int(input())
for i in range(usuarios):
    idade = int(input())
    nome = input()
    sexo = input()
    estado_civil = input()
    qtd_amigos = int(input())
    qtd_fotos = int(input())
    #print(' ')
    print(f'Idade: {idade}')
    print(f'Nome: {nome}')
    print(f'Sexo: {sexo}')
    print(f'Estado Civil: {estado_civil}')
    print(f'Numero de amigos: {qtd_amigos}')
    print(f'Numero de fotos: {qtd_fotos}\n')
